### ISSUE TITLE
undefined symbol: axi_dma_simple_unregister  

### ISSUE THREAD

**Issue by maximeborges** [hackwa/pynqfire#1]
Hello,
I tried [the example](https://github.com/hackwa/pynqfire/blob/master/notebooks/fir.ipynb) from the notebook directory but I'm not able to run it.
At 

    from fir import fir
    accel = fir()

I get this error:

    ---------------------------------------------------------------------------
    OSError                                   Traceback (most recent call last)
    <ipython-input-3-0447660a1355> in <module>()
        1 from fir import fir
    ----> 2 accel = fir()

    /opt/python3.6/lib/python3.6/site-packages/fir/fir.py in __init__(self)
        56         ffi = cffi.FFI()
        57         ffi.cdef("void _p0_cpp_FIR_0(void *din, void *dout, int dlen);")
    ---> 58         self.lib = ffi.dlopen(self.libfile)
        59         if PL.bitfile_name != self.bitfile:
        60                 self.download_bitstream()

    /opt/python3.6/lib/python3.6/site-packages/cffi/api.py in dlopen(self, name, flags)
        138         assert isinstance(name, basestring) or name is None
        139         with self._lock:
    --> 140             lib, function_cache = _make_ffi_library(self, name, flags)
        141             self._function_caches.append(function_cache)
        142             self._libraries.append(lib)

    /opt/python3.6/lib/python3.6/site-packages/cffi/api.py in _make_ffi_library(ffi, libname, flags)
        784 def _make_ffi_library(ffi, libname, flags):
        785     backend = ffi._backend
    --> 786     backendlib = _load_backend_lib(backend, libname, flags)
        787     #
        788     def accessor_function(name):

    /opt/python3.6/lib/python3.6/site-packages/cffi/api.py in _load_backend_lib(backend, name, flags)
        779         if first_error is not None:
        780             msg = "%s.  Additionally, %s" % (first_error, msg)
    --> 781         raise OSError(msg)
        782     return backend.load_library(path, flags)
        783 

    OSError: cannot load library /opt/python3.6/lib/python3.6/site-packages/fir/libfir.so: /opt/python3.6/lib/python3.6/site-packages/fir/libfir.so: undefined symbol: axi_dma_simple_unregister.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/opt/python3.6/lib/python3.6/site-packages/fir/libfir.so'

The file exist and is readable from anyone.
The symbol is effectively undefined in the `libfir.so`:

    # objdump -t libfir.so | grep axi_dma

    00000000       F *UND*	00000000              axi_dma_simple_open
    00000000       F *UND*	00000000              axi_dma_simple_send_i
    00000000         *UND*	00000000              axi_dma_simple_unregister
    00000000       F *UND*	00000000              axi_dma_simple_recv_i
    00000000       F *UND*	00000000              axi_dma_simple_close
    00000000         *UND*	00000000              axi_dma_simple_register

Do you have any clue on what is happening ?

**Comment by hackwa** [comment]
Hey maximeborges,

We have updated the code and bitstreams to support new Pynq-Z1 platforms. Please try now and let us know.

Anurag

**Comment by maximeborges** [comment]
Hey,
I'm still having a problem with the `libfir.so`. Now it's:
    
    OSError: cannot load library /opt/python3.6/lib/python3.6/site-packages/fir/libfir.so: /opt/python3.6/lib/python3.6/site-packages/fir/libfir.so: undefined symbol: sysport_open.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/opt/python3.6/lib/python3.6/site-packages/fir/libfir.so'

**Comment by hackwa** [comment]
I haven't seen these errors and I do not have information about what platform you're using.
Can you try and flash a fresh 2.1 image for Pynq and run pip install on that and retry the notebook?

**Comment by maximeborges** [comment]
I flashed the last Pynq image and it's ok now. Sorry for that !
